approve_by_comment: true
approve_regex: '^:\+1:'
reject_regex: '^(Rejected|:-1:)'
reject_value: -1
reset_on_push: true
author_approval: ignored
reviewers:
    required: 2
    teams:
        - pokemongo-bot-team
